# Generated by Django 3.0.4 on 2020-03-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
