# Generated by Django 3.0.4 on 2020-03-10 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='approvers',
            field=models.ManyToManyField(related_name='tickets_for_approval', through='django_tickets.Approval', to=settings.AUTH_USER_MODEL),
        ),
    ]
